INSERT INTO quantum.audit_trail (
  audit_id, source_row_id, event_ts, event_date, actor_type, actor_id, workflow_id, workflow_name, run_id, account_id, strategy_id, event_type, event_severity, event_status, entity_type, entity_id, message, before_state, after_state, raw_payload, ip_address, user_agent, correlation_id, idempotency_key, ingested_at
)
SELECT * FROM (VALUES
('tsm_1240207f_0'::text,NULL::text,'2026-08-06T13:45:22.906Z'::timestamptz,'2026-08-06'::date,'system','trailing_stop_manager','vFnPjyx8srnzcYgV','Trailing Stop Manager v2.0 (credential-migrated)','524111',NULL,'trailing_stop_manager','TRAILING_STOP_MANAGER','INFO','OK','position','ALLE','Trailing Stop Manager ORPHAN_ELIGIBLE_WINDOW_CLOSED ALLE',NULL::jsonb,NULL::jsonb,quantum.safe_jsonb('{"type":"ORPHAN_ELIGIBLE_WINDOW_CLOSED","sym":"ALLE","side":"long","qty":64,"entry":165.87,"activeStops":1,"recoveryStops":1,"recoveryClientOrderIds":["qtp_widestop_alle_1a4c4fc1"],"marketOpen":true,"carryoverWindow":false,"note":"orphan-reachable; flatten deferred until carryover window + market open","version":"QTP_TSM_ORPHAN_FLATTEN_v4.3.4_20260709","migration_version":"QTP_SUPABASE_TRAILING_STOP_MANAGER_v4.2.2","__recovered_from_exec":"524111"}'),NULL::text,NULL::text,'ALLE','tsm:524111:0:ALLE:ORPHAN_ELIGIBLE_WINDOW_CLOSED',CURRENT_TIMESTAMP),
('tsm_3b149d97_1',NULL,'2026-08-06T13:45:22.906Z','2026-08-06','system','trailing_stop_manager','vFnPjyx8srnzcYgV','Trailing Stop Manager v2.0 (credential-migrated)','524111',NULL,'trailing_stop_manager','TRAILING_STOP_MANAGER','INFO','OK','position','DGX','Trailing Stop Manager ORPHAN_ELIGIBLE_WINDOW_CLOSED DGX',NULL::jsonb,NULL::jsonb,quantum.safe_jsonb('{"type":"ORPHAN_ELIGIBLE_WINDOW_CLOSED","sym":"DGX","side":"long","qty":45,"entry":234.82,"activeStops":1,"recoveryStops":1,"recoveryClientOrderIds":["qtp_widestop_dgx_9d691dd7"],"marketOpen":true,"carryoverWindow":false,"note":"orphan-reachable; flatten deferred until carryover window + market open","version":"QTP_TSM_ORPHAN_FLATTEN_v4.3.4_20260709","migration_version":"QTP_SUPABASE_TRAILING_STOP_MANAGER_v4.2.2","__recovered_from_exec":"524111"}'),NULL,NULL,'DGX','tsm:524111:1:DGX:ORPHAN_ELIGIBLE_WINDOW_CLOSED',CURRENT_TIMESTAMP),
('tsm_0bb9f924_2',NULL,'2026-08-06T13:45:22.906Z','2026-08-06','system','trailing_stop_manager','vFnPjyx8srnzcYgV','Trailing Stop Manager v2.0 (credential-migrated)','524111',NULL,'trailing_stop_manager','TRAILING_STOP_MANAGER','INFO','OK','position','XPEV','Trailing Stop Manager ORPHAN_ELIGIBLE_WINDOW_CLOSED XPEV',NULL::jsonb,NULL::jsonb,quantum.safe_jsonb('{"type":"ORPHAN_ELIGIBLE_WINDOW_CLOSED","sym":"XPEV","side":"short","qty":858,"entry":12.415003,"activeStops":1,"recoveryStops":1,"recoveryClientOrderIds":["qtp_widestop_xpev_a24b9a15"],"marketOpen":true,"carryoverWindow":false,"note":"orphan-reachable; flatten deferred until carryover window + market open","version":"QTP_TSM_ORPHAN_FLATTEN_v4.3.4_20260709","migration_version":"QTP_SUPABASE_TRAILING_STOP_MANAGER_v4.2.2","__recovered_from_exec":"524111"}'),NULL,NULL,'XPEV','tsm:524111:2:XPEV:ORPHAN_ELIGIBLE_WINDOW_CLOSED',CURRENT_TIMESTAMP),
('tsm_37c7a739_3',NULL,'2026-08-06T13:45:22.906Z','2026-08-06','system','trailing_stop_manager','vFnPjyx8srnzcYgV','Trailing Stop Manager v2.0 (credential-migrated)','524111',NULL,'trailing_stop_manager','TRAILING_STOP_MANAGER','INFO','OK','position','AES','Trailing Stop Manager OCO_PROTECTED_AUDIT_SAFE AES',NULL::jsonb,NULL::jsonb,quantum.safe_jsonb('{"type":"OCO_PROTECTED_AUDIT_SAFE","sym":"AES","side":"short","qty":731,"protectedQty":731,"nestedStopCount":1,"stopDistancePct":0.0082,"action":"NO_ORDER_PLACED_ALREADY_PROTECTED","version":"QTP_TSM_HELD_BRACKET_STOP_VISIBILITY_v4.2.6","migration_version":"QTP_SUPABASE_TRAILING_STOP_MANAGER_v4.2.2","__recovered_from_exec":"524111"}'),NULL,NULL,'AES','tsm:524111:3:AES:OCO_PROTECTED_AUDIT_SAFE',CURRENT_TIMESTAMP),
('tsm_36e3aab3_4',NULL,'2026-08-06T13:45:22.906Z','2026-08-06','system','trailing_stop_manager','vFnPjyx8srnzcYgV','Trailing Stop Manager v2.0 (credential-migrated)','524111',NULL,'trailing_stop_manager','TRAILING_STOP_MANAGER','INFO','OK','position','WRB','Trailing Stop Manager UNPROTECTED_STOP_TOO_WIDE WRB',NULL::jsonb,NULL::jsonb,quantum.safe_jsonb('{"type":"UNPROTECTED_STOP_TOO_WIDE","sym":"WRB","side":"long","qty":148,"entry":73.05527,"current":72.085,"stopDistancePct":0.0305,"maxAllowedPct":0.012,"proposedStop":72.4,"nestedStopCount":1,"recovery":{"type":"STOP_TOO_WIDE_RECOVERY_FAILED_REVIEW_REQUIRED","sym":"WRB","error":"Request failed with status code 422 - {\"code\":42210000,\"market_price\":\"71.99\",\"message\":\"stop price must be less than current price\",\"stop_price\":\"72.4\"}","cancelled":["4c1cc11d-2b1f-43d7-859d-7aeb453f0a3a"],"cancelErrors":[],"recoveryKey":"stop_too_wide_recovery:WRB:e121c221"},"requiresManualReview":true,"version":"QTP_TSM_STOPWIDTH_EOD403_v4.3.0_20260706","migration_version":"QTP_SUPABASE_TRAILING_STOP_MANAGER_v4.2.2","__recovered_from_exec":"524111"}'),NULL,NULL,'WRB','tsm:524111:4:WRB:UNPROTECTED_STOP_TOO_WIDE',CURRENT_TIMESTAMP),
('tsm_4c25c648_5',NULL,'2026-08-06T13:45:22.906Z','2026-08-06','system','trailing_stop_manager','vFnPjyx8srnzcYgV','Trailing Stop Manager v2.0 (credential-migrated)','524111',NULL,'trailing_stop_manager','TRAILING_STOP_MANAGER','INFO','OK','position','XPEV','Trailing Stop Manager TRAILING_STOP_MANAGER_RUN XPEV',NULL::jsonb,NULL::jsonb,quantum.safe_jsonb('{"sym":"XPEV","tier":1,"tierLabel":"Breakeven + Scale Out","oldStop":12.53,"newStop":12.47,"entry":12.415003,"current":11.59,"atr":0.53,"gain":0.83,"gainPct":6.69,"migration_version":"QTP_SUPABASE_TRAILING_STOP_MANAGER_v4.2.2","__recovered_from_exec":"524111"}'),NULL,NULL,'XPEV','tsm:524111:5:XPEV:TRAILING_STOP_MANAGER_RUN',CURRENT_TIMESTAMP)
) AS v(audit_id, source_row_id, event_ts, event_date, actor_type, actor_id, workflow_id, workflow_name, run_id, account_id, strategy_id, event_type, event_severity, event_status, entity_type, entity_id, message, before_state, after_state, raw_payload, ip_address, user_agent, correlation_id, idempotency_key, ingested_at)
WHERE NOT EXISTS (SELECT 1 FROM quantum.audit_trail t WHERE t.idempotency_key = v.idempotency_key);
SELECT count(*) AS recovered, min(event_ts) AS event_ts,
  (SELECT raw_payload->>'__recovered_from_exec' FROM quantum.audit_trail WHERE audit_id='tsm_4c25c648_5') AS marker,
  (SELECT raw_payload->>'atr' FROM quantum.audit_trail WHERE audit_id='tsm_4c25c648_5') AS xpev_tier1_atr
FROM quantum.audit_trail WHERE run_id='524111';